{% set name = "prison" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/prison-{{ version }}.tar.gz
  sha256: a02b55719d033c4e7efc1d1660ed884a73743d89effb48205c5743c3c658b799

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.3
    - pip
  run:
    - python >=3.3
    - six

test:
  imports:
    - prison
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/betodealmeida/python-rison
  summary: Rison encoder/decoder
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xylar
