{% set name = "prison" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/prison-{{ version }}.tar.gz
  sha256: e6cd724044afcb1a8a69340cad2f1e3151a5839fd3a8027fd1357571e797c599

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.3
    - pip
  run:
    - python >=3.3
    - six

test:
  imports:
    - prison
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/betodealmeida/python-rison
  summary: Rison encoder/decoder
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xylar
